### ISSUE TITLE
Self-issued certificate isn't re-generated before expiry

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-gateway-android#266]
So courier sync will stop working when the certificate expires (it's current validity period is one year).

https://github.com/relaycorp/relaynet-gateway-android/blob/ec06dfc429e4db8e4cde02942c772486991c6898/app/src/main/java/tech/relaycorp/gateway/domain/LocalConfig.kt#L82-L91

**Comment by sdsantos** [comment]
@gnarea Just checked the current logic we have in place.

- We create a new identity certificate the first time the user uses the app
- Expired certificates are deleted automatically on every app start
- If we don't have an identity certificate, we generate and store a new one

So I feel we don't have this issue anymore.

Additionally, though I'm not entirely sure this is related:
- We store an identity certificate after registering with the public gateway
- If we get a CERTIFICATE_ROTATION cargo message from the Courier, we store the new identity certificate that comes inside it, if it expires later than the current one we have

**Comment by gnarea** [comment]
Thanks for looking into this @sdsantos!

The private gateway should have two certificates (for the same identity key pair):

- The one issued by its Internet gateway, which is used when the Internet is available (e.g., parcel collection via PoWeb).
- A self-issued one for the comms via couriers (cargo delivery and collection via CogRPC).

I think we're only talking about the latter here, in which case I agree this isn't an issue anymore if we're purging expired certificates and (re-)creating them on demand when syncing with couriers, so I'll close this issue.
