### ISSUE TITLE
Renew identity certificate over the Internet

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-gateway-android#507]
When the Internet is available and the current identity certificate is due to expire in the next <= 90 days, we should re-register with the public gateway using the existing key pair.

See:

https://github.com/relaycorp/relaynet-gateway-android/blob/d43d4df564f6721daa4ada3668cd0a8f546251b9/app/src/main/java/tech/relaycorp/gateway/domain/publicsync/RegisterGateway.kt#L55-L56

# What to do with old certificates

Old certificates should continue to be used in all signature verification operations, for as long as the certificates are valid. Namely:

- All calls to `parcel.validate()` and `cargo.validate()`. The old (yet valid) certificates should be passed as `trustedCertificates`, along with the new certificate.
- The WebSocket-based, parcel collection endpoint in the PDC server: https://github.com/relaycorp/relaynet-gateway-android/blob/960f9467c812cbb70975e66e63ab980882554b00/app/src/main/java/tech/relaycorp/gateway/pdc/local/utils/ParcelCollectionHandshake.kt#L43 The old and new certificates should be included in the `trustedCertificates`.

Old certificates should only be deleted after they expire (e,g., once a day, when the app starts). However, expired certificates must not be included in the `trustedCertificates` above.

# What to do with the new certificate

The new certificate should be used in all signature verification operations (see above), as well as signature generation operations (i.e., `parcel.serialize()`, `cargo.serialize()`, `issueEndpointCertificate()`).

This shouldn't require code any further code changes, but I'm documenting this requirement to make sure we don't change the code inadvertently.

# Related issues

- #508 is the offline counterpart.
- #539

**Comment by sdsantos** [comment]
Tasks:
- [ ] Add support for multiple identity certificates, or at least one additional backup one
- [ ] Register new certificate when current is about to expire
- [ ] Use the latest certificate in all signature generation operations
- [ ] Use all valid certificates in signature verification operations
- [ ] Delete expired certificates on app start
