### ISSUE TITLE
Save incoming id certificate renewals received via couriers

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-gateway-android#508]
Only reason not to save it is if we already have a newer certificate.

Note that we should also replace our copy of the public gateway's id certificate as it may have changed too.

## Related issues

- This issue is blocked by https://github.com/relaycorp/relaynet-internet-gateway/issues/675
- #507 is the online counterpart to this issue.
- #539

**Comment by sdsantos** [comment]
This task requires the ability to have multiple identity certificates, from https://github.com/relaycorp/relaynet-gateway-android/issues/507

Tasks:
- [ ] Save incoming identity certificates renewals received via couriers

**Comment by gnarea** [comment]
I already implemented the server-side changes in https://github.com/relaycorp/relaynet-internet-gateway/pull/737, so the only external change needed before implementing this is https://github.com/relaycorp/awala-jvm/pull/221.

With https://github.com/relaycorp/awala-jvm/pull/221, we'll just have to add a case for `CertificateRotation` in:

https://github.com/relaycorp/relaynet-gateway-android/blob/d43d4df564f6721daa4ada3668cd0a8f546251b9/app/src/main/java/tech/relaycorp/gateway/domain/courier/ProcessCargo.kt#L40-L47
