### ISSUE TITLE
Notify local endpoints when the gateway's id certificate is renewed

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-gateway-android#539]
So that those endpoints can re-register at their earliest convenience.

This could be implemented as an Android broadcast, for example.

# When it should be triggered

- When the certificate is renewed via the Internet (see: #507).
- When the certificate is renewed via couriers (see: #508).

However it's implemented, it should ideally be generic enough to be reused more generally when the certificate changes for  other reasons (e.g., the user migrated to another public gateway), although triggering the notification for other reasons is outside the scope of this issue.

**Comment by sdsantos** [comment]
Requires:
- https://github.com/relaycorp/relaynet-gateway-android/issues/507
- https://github.com/relaycorp/relaynet-gateway-android/issues/508

Tasks:
- [ ] Whenever there's a renewal, send a broadcast to all endpoints
