### ISSUE TITLE
Cargo Delivery Authorisation issuer isn't rotated

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-gateway-android#571]
I forgot to call this out explicitly in the issues: We should rotate the self-issued certificate used in Cargo Delivery Authorisations.

Right now, we can only have exactly one as it's stored in a file that's generated the first time the app starts (and there's no rotation):
https://github.com/relaycorp/relaynet-gateway-android/blob/809ebbe4452375efb2514d146bb5b5eb86fecbfe/app/src/main/java/tech/relaycorp/gateway/domain/LocalConfig.kt#L116

Instead, we should do what we've been doing with the other certificates:

- Generate a new one when the latest one is about to expire.
- Use the latest certificate in all signature-producing operations. In this case, only here:
  https://github.com/relaycorp/relaynet-gateway-android/blob/8f01a2b0895c173a422b52da0d1e8bbd26c4e176/app/src/main/java/tech/relaycorp/gateway/domain/courier/GenerateCCA.kt#L27-L32
- Use all the valid certificates in all signature-verification operations. In this case, only here:
  https://github.com/relaycorp/relaynet-gateway-android/blob/c56cc7147c006c43e9d951e1d7814610ae8ba705/app/src/main/java/tech/relaycorp/gateway/data/disk/CargoStorage.kt#L30
- Delete all expired certificates.

We probably want to reuse our `FileCertificateStore` and introduce a second instance to manage CDA issuers only. I think that'd require changing the `FileCertificateStore` class to take a path prefix (under the existing root), so that we avoid overriding files.

**Comment by sdsantos** [comment]
Tasks:

- [ ] Create second instance of `FileCertificateStore` for storing CDAs
- [ ] Switch from regular FileStore to FileCertificateStore for storing CDAs
- [ ] Generate new CDA when we don't have any, or the one we have stored is about to expire
- [ ] Method to return the latest valid CDA and use it in all signature-producing operations
- [ ] Method to return all valid CDAs and use it in all signature-verification operations
- [ ] Delete all expired certificates on app start
