### ISSUE TITLE
Logs from PoWeb library are not output

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-gateway-android#709]
For example, [we have some INFO logs when collecting parcels](https://github.com/relaycorp/awala-poweb-jvm/blob/380529fb1028ff22dc8da843223d66a9e90a26f7/src/main/kotlin/tech/relaycorp/poweb/PoWebClient.kt#L317-L329), but they're not shown on logcat.

I guess we have to configure Log4j or something like it, but I tried to configure Log4j and couldn't make it work.

**Comment by sdsantos** [comment]
Closed by https://github.com/relaycorp/awala-poweb-jvm/pull/305
